services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\GitlabConnectorBundle\:
        resource: '../../*'
        exclude:
          - '../../{Resources}'
