services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\GitlabConnector\:
        resource: '../../*'
        exclude:
          - '../../{Migrations}'
          - '../../{Resources}'
